- name: install hpts
  community.general.npm:
    name: http-proxy-to-socks

- name: make an service
  template:
    src: "ss.service.j2"
    dest: "~/.config/systemd/user/sslocal-kcp.service"

- name: start
  systemd:
    name: "sslocal-kcp"
    daemon_reload: yes
    state: started
    enabled: yes
    scope: user
