# kcp
- name: create kcp dir
  file:
    path: "{{kcp_path}}/{{kcp_version}}"
    state: directory
  become: true

# download if not exists
- name: check if kcp is installed
  stat: path="{{kcp_path}}/{{kcp_version}}/{{kcp_bin}}"
  register: p_kcp
  become: true

- name: install kcp
  unarchive:
    src: "https://github.com/xtaci/kcptun/releases/download/v{{kcp_version}}/kcptun-linux-{{kcp_arch}}-{{kcp_version}}.tar.gz"
    dest: "{{kcp_path}}/{{kcp_version}}"
    remote_src: True
  when: p_kcp.stat.exists is defined and not p_kcp.stat.exists
  become: true

- import_role:
    name: cmd-service
  vars:
    name: kcp
    cmd: "{{kcp_path}}/{{kcp_version}}/{{kcp_bin}} -r '{{kcp_server}}:{{kcp_port}}' -l ':{{kcp_local_port}}' -key '{{kcp_password}}' -mtu 1400 -sndwnd 106 -rcvwnd 2048 -mode fast2"
