# ss
# - name: ss repo
#   apt_repository:
#     repo: "ppa:max-c-lv/shadowsocks-libev"
#   become: true

- name: install ss
  apt:
    name: shadowsocks-libev
  become: true

- name: dont need ss server
  service:
    name: shadowsocks-libev
    enabled: false
    state: stopped

- import_role:
    name: cmd-service
  vars:
    name: sslocal-kcp
    cmd: "/usr/bin/ss-local -s 127.0.0.1 -p {{kcp_local_port}} -k '{{ss_password}}' -b {{ss_local_ip}} -l {{ss_local_port}} -m chacha20-ietf-poly1305"
